### ISSUE TITLE
Bug: Cannot call the server

### ISSUE THREAD

**Issue by biplobmanna** [unum-cloud/ujrpc#22]
### Describe the bug

After creating a custom server in python using `ujrpc` and starting the server, on sending a request server terminates.

This also happens while using `examples/sum/ujrpc_server.py` directly from inside the codebase.

SERVER:
![ujrpc-server](https://user-images.githubusercontent.com/5135690/223643303-d9a37a0a-9fd7-400e-bf87-ecbbf0780ca0.png)

CLIENT (cURL):
![ujrpc-curl](https://user-images.githubusercontent.com/5135690/223643378-2e6c44fe-4234-4c19-a250-1704e5964b2a.png)

> Tried sending request using cURL, Postman with & without any data.

However, running the benchmarks run successfully.
![ujrpc-benchmark](https://user-images.githubusercontent.com/5135690/223643680-a2e602e8-2962-4b1e-82dd-9a5e133362a8.png)

### Steps to reproduce

System: W11, WSL2
Python 3.10.6
pip 23.0.1
virtualenv 20.20.0

1. Clone the project
2. Create a virtual environment & source it
3. install all required packages `pip install uvicorn fastapi websocket-client requests tqdm fire`
4. run the server `python examples/sum/ujrpc_server.py`
5. request using cURL or Postman 

### Expected behavior

1. Calling with / without data should not terminate the server
2. Calling with proper data & method should return valid data

### UJRPC version

0.0.9

### Operating System

W11-WSL2-Ubuntu22.04

### Hardware architecture

x86

### Which interface are you using?

Official Python bindings

### Which implementation are you using?

POSIX

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
Thanks for reporting!
The benchmark and the server you are trying to run are unrelated to each other, but that is not the issue. Apparently, you are using an old CPU, and one of the SIMD-accelerated libraries uses an instruction not present in your ISA. 
Which generation/model CPU are you using?

**Comment by biplobmanna** [comment]
> Thanks for reporting! The benchmark and the server you are trying to run are unrelated to each other, but that is not the issue. Apparently, you are using an old CPU, and one of the SIMD-accelerated libraries uses an instruction not present in your ISA. Which generation/model CPU are you using?


```
CPU: Intel i5 8250U
OS: W11 build 22621
```

**Comment by thomanq** [comment]
I also get `Illegal instruction (core dumped)`.
CPU: `AMD Ryzen 7 4800U`
Kernel: `Linux 6.2`
Python `3.11.0`
implementation: `Posix`
ujrpc `0.2.3`

**Comment by ashvardanian** [comment]
With more than one dependency it will be really hard to implement dynamic dispatch... @ishkhan42 should we hardcode a couple of target architectures, for x86 and Arm instead of the current `-march=native`? If by any chance the build happens on an Ice Lake CPU, that would generate unsupported AVX-512 instructions, and cause the issues our users are facing.

**Comment by ashvardanian** [comment]
We have managed to replicate the issue on the Ryzen machine. It seems to be coming from `simdjson`. We will try a couple more solutions and will deliver a patch ASAP. That's our highest priority now.

**Comment by ishkhan42** [comment]
The error message `Illegal instruction (core dumped)` was coming from `simdjson`. We upgraded to the latest version, and it appears that the issue has been resolved.
I suggest that you try again after the new version is released and see if the problem is resolved on your end.

**Comment by ashvardanian** [comment]
We have just pushed a patch to PyPi. @thomanq and @biplobmanna, can you please try again with the following command:

```sh
pip install --force-reinstall ujrpc==0.2.7
```

@thomanq, I'm also curious how this would perform on your machine. I've never tested this on kernel 6.2, but it might be hard to get consistent measurements assuming the large spread between the 1.8 GHz base and 4.2 GHz turbo clocks :thinking:

**Comment by thomanq** [comment]
Using that code from the README:
```
from ujrpc.posix import Server
# from ujrpc.uring import Server # on 5.19+
server = Server()

@server
def sum(a: int, b: int):
    return a + b

server.run()
```
I still get:
```
Initialized server: 0.0.0.0:8545
- 1 threads
- 1 max concurrent connections
Illegal instruction (core dumped)
```
when visiting `http://localhost:8545/`.
I guess it should be a 404? 
Same issue visiting `http://localhost:8545/sum` or `http://localhost:8545/sum?a=1&b=2`

I reinstalled with the above command.
```
$ pip show ujrpc
Name: ujrpc
Version: 0.2.7
```
Trying to use ujrpc.uring I get a ModuleNotFoundError. Not sure what I'd have to do to test that.
```
from ujrpc.uring import Server # on 5.19+
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ujrpc.uring'
```

```
$ pip freeze
numpy==1.24.2
Pillow==9.4.0
ujrpc==0.2.7
```

**Comment by ashvardanian** [comment]
Thank you, @thomanq! We will follow up soon.

---

As for the endpoint, it will remain `http://localhost:8545/` for all endpoints.
Unlike REST, with JSON-RPC, the function name and arguments are always provided in the payload, and not in the URI.

**Comment by ishkhan42** [comment]
The `Illegal instruction (core dumped)` issue is likely to have been resolved in the relevant branch.

**Comment by ishkhan42** [comment]
To address the missing `uring` module, it may be necessary to drop support for `Python<=3.8`. This will allow the use of manylinux with `libc>=2.28` to build `liburing` without complications.

You may check latest, once released.

**Comment by thomanq** [comment]
Thanks!
I installed `0.2.8`.
Here is the new behavior:
- with `from ujrpc.uring import Server`
```
Initialized server: 0.0.0.0:8545
- 16 threads
- 1024 max concurrent connections
Segmentation fault (core dumped)
```
- with `from ujrpc.posix import Server` it's not failing anymore, but I get an empty response.
Could you please add the exact `curl` command needed to run the `sum` example in the README?
```
curl -X POST  -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","id":1,"method":"sum","params":{"a":2,"b":3}' http://localhost:8545/
curl: (52) Empty reply from server
```
I'm not sure my request is well-formed.

**Comment by ashvardanian** [comment]
@thomanq that's progress 😅
I am glad we’ve passed that stage! Is it the same with a single-threaded server? Are you using the C or Python version? 

Let’s limit this to the simplest reproducible case. 

Obviously “SIMD + Linux 5.19" doesn’t play very well with the whole “ManyLinux” and "compatibility” theme. We have already tried a few different builds and I believe there is a compromise to be reached. Thank you for helping us find it ☺️

**Comment by thomanq** [comment]
Actually `uring` 16 threads does not segfault.
I think it was due to the way I was getting rid of the previous runs with Ctrl + z.
Now I kill the process afterwards (`kill -9 <pid>`) and it doesn't seem to segfault.
(Btw, if you could land https://github.com/unum-cloud/ujrpc/issues/47 soonish that'd help with experimentation ^^)
I get
```
curl -X POST  -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","id":1,"method":"sum","params":{"a":2,"b":3}' http://localhost:8545/
curl: (8) Invalid Content-Length: value
```
same with one thread when I launch with
```
server = Server(max_threads=1)
```
I get
```
Initialized server: 0.0.0.0:8545
- 1 threads
- 1024 max concurrent connections
```
and curl:
```
curl -X POST  -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","id":1,"method":"sum","params":{"a":2,"b":3}' http://localhost:8545/
curl: (8) Invalid Content-Length: value
```
So: 
- segfaults can be caused by previous runs that are stopped with Ctrl+z but not killed
- It seems that when passing a `port` to the Server but not changing `max_threads` like `Server(port=8889)` it defaults to 1 thread instead of 16, that's a bit unexpected

Note: I'm more of a Python person so my C/C++ reading skills are a bit limited, but I'll try to help.
I'm using the Python version from the README.

**Comment by biplobmanna** [comment]
> We have just pushed a patch to PyPi. @thomanq and @biplobmanna, can you please try again with the following command:
> 
> ```shell
> pip install --force-reinstall ujrpc==0.2.7
> ```
> 
> @thomanq, I'm also curious how this would perform on your machine. I've never tested this on kernel 6.2, but it might be hard to get consistent measurements assuming the large spread between the 1.8 GHz base and 4.2 GHz turbo clocks 🤔

Unfortunately, this is not working. I'm getting the same illegal instruction.
```text
Initialized server: 0.0.0.0:8545
- 1 threads
- 1 max concurrent connections
Illegal instruction
```

However, I've installed version `0.2.8` and that seems to be working for the examples. 

I will play around a bit more when I'm free and update.

**Comment by biplobmanna** [comment]
### Trying with `ujrpc.uring`:

I'm getting **segfaults** for every case.

Killed all processes previously exited -> still segfault.
Restarted WSL and redo -> still segfault
`max_threads=8` -> still segfault
`max_threads=1` -> still segfault

Maybe this issue is with WSL? 🤔 

Also, slight correction to the cURL request. It was missing a `}` in the data portion.

```text
curl -X POST  -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","id":1,"method":"sum","params":{"a":2,"b":3}}' http://localhost:8545/
```

I generally use Postman for these, and here's the full cURL for that (if it helps):
```bash
curl --location 'http://localhost:8545' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc":"2.0",
    "id": 1,
    "method":"sum",
    "params": {
        "a": 2,
        "b": 3
    }
}'
```

**Comment by ishkhan42** [comment]
As we have not tested on `WSL`, it is difficult to predict what issues may arise.
@biplobmanna it would be better to open a separate feature request specifically for `WSL`. 
Similarly, if @thomanq encounters any other reproducible issues, new issues should be opened accordingly.

However, it appears that the specific issue related to `Illegal instruction (core dumped)` has been resolved, so i guess this issue can be closed @ashvardanian.

**Comment by ashvardanian** [comment]
Splitting those threads into separate issues makes sense.
At this point, @thomanq, we are working on #47.
There is one more issue that you may encounter that we are familiar with - #57.

> defaults to 1 thread instead of 16, that's a bit unexpected

As for this, I think it's as it should be. At 200K requests/second, more threads add more synchronization. The bottleneck is in the TCP/IP stack itself, and adding threads to process lightweight responses doesn't help, even in C.

It's even worse with Python, which always operates under the Global Interpreter Lock. So you can only generally have up to 1 active Python thread per process, at least in Python 3. Fingers crossed for Python 4 🤞 

The only time many threads make sense - is with heavy callbacks connected directly to our C layer, without CPython in between.

**Comment by thomanq** [comment]
> Also, slight correction to the cURL request. It was missing a } in the data portion.

thanks @biplobmanna  ^^
I was a bit blind. That fixes it.

@ashvardanian  you were interested in benchmarks.
If you have some commands you'd like me to run, please let me know.

**Comment by thomanq** [comment]
I think `uring` is not fixed completely yet.
```
posix 1  thread 1    max connection  46844.99 requests/sec
uring 1  thread 1024 max connections  11.14 requests/sec timeouts 1-3
uring 16 thread 1024 max connections  16.51 requests/sec timeouts 1-3
```
Here is how I benchmarked:
`wrk -t12 -c400 -d30s http://127.0.0.1:8545 -s post.lua`
with following `post.lua` script:
```
wrk.method = "POST"
wrk.body   = "{\"jsonrpc\":\"2.0\",\"id\":11,\"method\":\"sum\",\"params\":{\"a\":2,\"b\":100}}"
wrk.headers["Content-Type"] = "application/json"
```
For comparison, with [starlette](https://github.com/encode/starlette) or [granian](https://github.com/emmett-framework/granian) and simple queries, I can reach 90k-100k requests/sec on my machine.

If there is an obvious flaw in the script above, please let me know.
Also I don't think max_connections is exposed in `uring` Server? I wasn't able to test `uring 1  thread 1 max connection`.

**Comment by ashvardanian** [comment]
@thomanq Something is wrong there. Can you try setting the `Content-Length` header as well?

**Comment by thomanq** [comment]
I'm not able to benchmark, sorry.

I've tried both `wrk` and `ab` and I can't come up with a command that gives me results.

Here is what I've tried:
`wrk -t12 -c400 -d30s http://127.0.0.1:8545 -s post.lua`
with following `post.lua` or small variations thereof
```
wrk.method = "POST"
wrk.body   = '{"jsonrpc":"2.0","id":11,"method":"sum","params":{"a":2,"b":100}}'
wrk.headers["Content-Type"] = "application/json"
wrk.headers["Content-Length"] = 65
wrk.headers["Accept"] = "*/*"
wrk.headers["User-Agent"] = "curl/7.87.0"
```
Even with the `posix` implementation, the results I got earlier get `Socket errors: read 1327228` which I previously oversaw.
```
Running 30s test @ http://127.0.0.1:8545
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     8.87ms    1.22ms  43.04ms   76.42%
    Req/Sec     3.70k   340.39     4.75k    72.82%
  1327229 requests in 30.07s, 146.83MB read
  Socket errors: connect 0, read 1327228, write 0, timeout 0
Requests/sec:  44144.01
Transfer/sec:      4.88MB
```
`uring` stuck at:
```
Running 30s test @ http://127.0.0.1:8545
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     5.56ms   16.05ms  60.53ms   91.61%
    Req/Sec   685.75    583.39     1.20k    75.00%
  274 requests in 30.09s, 28.66KB read
  Socket errors: connect 0, read 76, write 0, timeout 0
Requests/sec:      9.11
Transfer/sec:      0.95KB
```
If you have benchmarking commands for me to run, I can try.
Otherwise I give up on the benchmarks. :)
